data_folder: ../data/gnn_pretraining/dev

vocabulary:
  name: "vocabulary.pkl"
  n_tokens: 8917

data:
  batch_size: 128
  test_batch_size: 256
  max_token_parts: 5
  task:
    name: "masking"
    p_node: 0.5
    p_edge: 0.5