data_folder: ../data/gnn_pretraining/xglue-code-to-text-python-dev

resume_from_checkpoint: null

seed: 7
offline: true
# Training in notebooks (e.g. Google Colab) may crash with too small value
progress_bar_refresh_rate: 1

node_tokenizer: "../pretrain/tokenizer.json"
label_tokenizer: "label_tokenizer.json"

pretrained_weights: "../data/gnn_pretraining/pretrain/pretrained_weights.ckpt"

data:
  num_workers: 0
  batch_size: 10
  test_batch_size: 5
  max_token_parts: 5
  max_n_nodes: 4000
  task:
    name: "sequence generating"
    field: "docstring"

model:
  embed_dim: 10
  hidden_dim: 10
  n_hidden_layers: 1
  decoder:
    decoder_num_layers: 1
    embedding_size: 10
    decoder_size: 10
    rnn_dropout: 0.3


optimizer:
  lr: 0.01
  weight_decay: 0
  decay_gamma: 0.95

train:
  n_epochs: 5
  patience: 10
  clip_norm: 10
  teacher_forcing: 1.0
  val_every_step: 1.0
  log_every_n_steps: 10
