data_folder: ../data/graphs/xglue-code-to-text-python

resume_from_checkpoint: null

seed: 7
offline: false
# Training in notebooks (e.g. Google Colab) may crash with too small value
progress_bar_refresh_rate: 1

node_tokenizer: "../full/tokenizer.json"
label_tokenizer: "label_tokenizer.json"

pretrained_weights: "../data/graphs/full/pretrained_weights.ckpt"

data:
  num_workers: -1
  batch_size: 256
  test_batch_size: 384
  max_token_parts: 5
  max_n_nodes: 4000
  task:
    name: "sequence generating"
    field: "docstring"

model:
  embed_dim: 128
  hidden_dim: 128
  n_hidden_layers: 3
  decoder:
    decoder_num_layers: 1
    embedding_size: 128
    decoder_size: 128
    rnn_dropout: 0.3


optimizer:
  lr: 0.01
  weight_decay: 0
  decay_gamma: 0.95

train:
  n_epochs: 300
  patience: 10
  clip_norm: 10
  teacher_forcing: 1.0
  val_every_step: 1.0
  log_every_n_steps: 10
